Adding Run 3 paths
cms-tau-pog/NanoProd pull request #16
Opened 2023-06-29 13:15 UTC by IreneAndreou

2023-06-29 13:19 UTC, cardinia commented on NanoProd/crab/overseer_cfg.yaml
Hi @IreneAndreou , since the paths have been modified in this config file I think it is worth taking the chance to generalize them using $user or other environment variables to generalize the config file

2023-06-29 13:20 UTC, cardinia commented
Hi @IreneAndreou , I see that several filelists include a lot of commented lines, is this intentional?

2023-06-29 13:28 UTC, IreneAndreou commented on NanoProd/crab/overseer_cfg.yaml
Hi @cardinia, thank you for the comments! That's a good idea; I'll try and add a $user variable. The commented lines are there because I couldn't find those specific MC file paths.

2023-06-29 14:25 UTC, kandrosov requested changes

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022/DY.yaml
> +#DYJetsToLL_M-10to50-madgraphMLM: /DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
here and in other configs: remove commented lines that correspond to 2018 datasets. If needed in the future, you can always make diff between 2022 vs UL

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022/SingleTop.yaml
> +#ST_tW_antitop_5f_NoFullyHadronicDecays: /ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
remove empty config

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022/W.yaml
> +# WJetsToLNu: /WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
IMO, if we don't have tt semileptonic and W, it makes no sense to start the production...

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022/Z.yaml
> +# ZJetsToNuNu_HT-100To200: /ZJetsToNuNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
remove empty config

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022/data.yaml
> +EGamma_Run202C_rereco: /EGamma/Run2022C-10Dec2022-v1/MINIAOD
rereco is bugged, or I'm mistaken?

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022/data.yaml
> +SingleMuon_Run2022C_rereco: /SingleMuon/Run2022C-10Dec2022-v2/MINIAOD
D for SingleMuon?

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022/data.yaml
> +JetHT_Run2022C: /JetHT/Run2022C-PromptReco-v1/MINIAOD
D for JetHT?

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022/data.yaml
> +MET_Run2022C: /MET/Run2022C-PromptReco-v1/MINIAOD
D for MET?

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/QCD.yaml
> +# QCD_HT50to100: /QCD_HT50to100_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
remove empty config

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/SingleTop.yaml
> +# ST_tW_antitop_5f_NoFullyHadronicDecays: /ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
remove empty config

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/Triboson.yaml
> +
remove empty config

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/W.yaml
> +# WJetsToLNu: /WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
remove empty config

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/Z.yaml
> +# ZJetsToNuNu_HT-100To200: /ZJetsToNuNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
remove empty config

2023-06-29 14:25 UTC, kandrosov commented on NanoProd/crab/overseer_cfg.yaml
> +localCrabOutput: /eos/cms/store/group/phys_tau/irandreo/Run3_22
`finalOutput` and `localCrabOutput` should be different folders.

2023-06-29 14:25 UTC, kandrosov commented on env_13_0.sh
> +#!/usr/bin/env bash
remove this file. use `env.sh`

2023-07-14 14:38 UTC, kandrosov requested changes

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022/DY.yaml
> +DYJetsToLL_M-50-madgraphMLM: /DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Summer22MiniAODv3-forPOG_124X_mcRun3_2022_realistic_v12-v4/MINIAODSIM
Add:
```
/DYTo2L_MLL-4to50_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
/DYTo2L_MLL-50_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
/DYto2TautoMuTauh_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
```

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022/TT.yaml
> +TTTo2L2Nu: /TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v4/MINIAODSIM
Add
```
/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v5/MINIAODSIM
/TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v4/MINIAODSIM
/TT_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12_ext1-v3/MINIAODSIM
/TT_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v3/MINIAODSIM
```

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022/Triboson.yaml
> +ZZZ: /ZZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
Add:
```
/WWW_4F_TuneCP5_13p6TeV_amcatnlo-madspin-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
/WWZ_4F_TuneCP5_13p6TeV_amcatnlo-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
/WZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
```
- where is Triboson for postEE?

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022/data.yaml
> +EGamma_Run202C: /EGamma/Run2022C-PromptReco-v1/MINIAOD
remove this file. Will process CDE once re-rereco is ready.

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/DY.yaml
> +DYJetsToLL_M-50-madgraphMLM: /DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Summer22EEMiniAODv3-forPOG_124X_mcRun3_2022_realistic_postEE_v1-v3/MINIAODSIM
Add:
```
/DYto2TautoMuTauh_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v2/MINIAODSIM
```

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/SMHiggs.yaml
> +
where is SMHiggs for pre-EE?

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/TT.yaml
> +TTTo2L2Nu: /TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v2/MINIAODSIM
Add:
```
/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v2/MINIAODSIM
/TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v3/MINIAODSIM

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/data.yaml
> +EGamma_Run2022E_rereco: /EGamma/Run2022E-10Dec2022-v3/MINIAOD
```suggestion
```

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/data.yaml
> +Tau_Run2022E_rereco: /Tau/Run2022E-10Dec2022-v2/MINIAOD
```suggestion
```

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/data.yaml
> +MuonEG_Run2022G: /MuonEG/Run2022G-PromptReco-v1/MINIAOD
- Why do we need MuonEG?
- Add Muon F&G

2023-07-14 14:38 UTC, kandrosov commented on NanoProd/python/customize.py
> +    for vs, wp, score in [ ("e", "VVVLoose", "0.099"), ("mu", "VLoose","0.2949"), ("jet", "VVVLoose","0.4083") ]:
Import the python config with WPs instead of hardcoding the numbers.

2023-07-19 14:03 UTC, kandrosov requested changes

2023-07-19 14:03 UTC, kandrosov commented on NanoProd/crab/Run3_2022/W.yaml
> +WtoLNu-2Jets: /WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v3/MINIAODSIM
```suggestion
WtoLNu_amcatnloFXFX: /WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v3/MINIAODSIM
```

2023-07-19 14:03 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/data.yaml
> +#EGamma_Run2022E_rereco: /EGamma/Run2022E-10Dec2022-v3/MINIAOD
```suggestion
```

2023-07-19 14:03 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/data.yaml
> +#Tau_Run2022E_rereco: /Tau/Run2022E-10Dec2022-v2/MINIAOD
```suggestion
```

2023-07-19 14:03 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/data.yaml
> +#MuonEG_Run2022E_rereco: /MuonEG/Run2022E-10Dec2022-v2/MINIAOD
```suggestion
```

2023-07-19 14:03 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/data.yaml
> +MuonEG_Run2022G: /MuonEG/Run2022G-PromptReco-v1/MINIAOD
- why do we need MuonEG?
- Add JetHT and MET

2023-07-19 14:03 UTC, kandrosov commented on RunKit
update RunKit to main

2023-07-19 14:03 UTC, kandrosov commented on NanoProd/crab/Run3_2022/data.yaml
> +# EGamma_Run202C: /EGamma/Run2022C-PromptReco-v1/MINIAOD
Remove this file - all datasets here are "not usable".

2023-07-19 14:03 UTC, kandrosov commented on NanoProd/crab/Run3_2022_postEE/W.yaml
> +WtoLNu-2Jets: /WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v3/MINIAODSIM
```suggestion
WtoLNu_amcatnloFXFX: /WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v3/MINIAODSIM
```

2023-07-19 14:05 UTC, kandrosov commented on NanoProd/crab/overseer_cfg.yaml
This can be implemented in the future. I think it is ok for this PR to have the folder name hardcoded.

2023-07-21 09:48 UTC, kandrosov approved these changes

2023-07-21 09:56 UTC, merged