Changes for Tau-embedded samples
cms-tau-pog/NanoProd pull request #18
Opened 2023-07-31 14:33 UTC by DennRoy

In order to run Tau-embedded samples, an additional customization is required. This customization is based on [these instructions](https://twiki.cern.ch/twiki/bin/viewauth/CMS/TauEmbeddingSamplesUL#NanoAOD_Conversion), but contain some modifications in order for this to work with a newer CMSSW version and NanoAOD v12.

The easiest way to process embedded samples is to run them separately from data or MC, by using a separate overseer config. The differences compared to the nominal config are the path to the additional customization, and points to a different DBS instance ("phys03" instead of "global").

This PR is not ready to be merged, as I would like embedding experts to sign off on the customizations added here.

2023-08-14 09:55 UTC, kandrosov commented
@DennRoy, there is a possibility to redefine parameters in the samples' yaml files. I think having a separate `overseer_cfg_embeddedSamples.yaml` is overkill. If redefine doesn't work for some reason, please, let me know, and I'll try to fix it on the RinKit side.
Please add yaml files with embedded samples for Run 2 eras to this PR

2023-08-16 11:07 UTC, DennRoy commented
Thanks! I was able to successfully redo the test by adding those parameters to the yaml files, also testing the new pfns prefix argument.

2023-08-16 15:13 UTC, kandrosov requested changes
Thank you @DennRoy ! Modifications look fine. Please update the RunKit sub-module to the current RunKit/main.

2023-08-16 15:13 UTC, kandrosov commented on NanoProd/crab/Run2_2016/Embedded.yaml
> +    sampleType: data
Have you checked that, with `sampleType: data`, the MC truth information for taus is stored?

2023-08-17 15:25 UTC, DennRoy commented on NanoProd/crab/Run2_2016/Embedded.yaml
> +    sampleType: data
I compared the list of branches in the embedded output to those produced from the example file in the Readme (`/eos/cms/store/group/phys_tau/kandroso/miniAOD_UL18/TTToSemiLeptonic.root`), using the skim config `skim_htt.yaml`. Many gen-level branches are in the embedded output, but there are a few branches missing:

```'Pileup_nPU', 'Pileup_sumEOOT', 'Pileup_sumLOOT', 'genTtbarId', 'nGenJetAK8', 'nSubGenJetAK8', 'FatJet_genJetAK8Idx', 'FatJet_hadronFlavour', 'FatJet_nBHadrons', 'FatJet_nCHadrons', 'Flag_BadPFMuonDzFilter', 'Flag_hfNoisyHitsFilter', 'GenJetAK8_eta', 'GenJetAK8_hadronFlavour', 'GenJetAK8_mass', 'GenJetAK8_partonFlavour', 'GenJetAK8_phi', 'GenJetAK8_pt', 'GenJet_hadronFlavour', 'GenJet_partonFlavour', 'GenMET_phi', 'GenMET_pt', 'L1Reco_step', 'L1simulation_step', 'Pileup_gpudensity', 'Pileup_nTrueInt', 'Pileup_pudensity', 'SubGenJetAK8_eta', 'SubGenJetAK8_mass', 'SubGenJetAK8_phi', 'SubGenJetAK8_pt', 'SubJet_hadronFlavour', 'SubJet_nBHadrons', 'SubJet_nCHadrons'```

I'll try looking into it.

2023-08-18 07:05 UTC, kandrosov commented on NanoProd/crab/Run2_2016/Embedded.yaml
> +    sampleType: data
It is fine - since for embedded samples only taus are generated, the gen branches you've listed above are undefined.

2023-08-18 13:29 UTC, kandrosov commented
@DennRoy do you plan any other updates? If not, I am ok with merging this PR

2023-08-18 14:13 UTC, DennRoy commented on NanoProd/crab/Run2_2016/Embedded.yaml
> +    sampleType: data
I'm actually not sure about the two MET filter flags `Flag_BadPFMuonDzFilter` and `Flag_hfNoisyHitsFilter`, or the FatJet variables, I would have expected those to be in the output too

2023-08-18 14:16 UTC, DennRoy commented
The people from KIT are still looking into my suggested customization. They say it looks alright, but didn't get to directly compare the outputs yet with what they have.

2023-09-13 10:59 UTC, DennRoy commented
It all works fine so far, but there's still one more issue related to some trigger bit information (IDs which were 15 for Taus before are not always that value anymore in nAODv12). I've been told that this could be related to some special trigger, which is also not yet implemented. The people at KIT are still working on this.
In any case, if we don't have this special trigger yet, there won't be a point to processing all of the embedded samples yet, so I'd suggest to keep this PR open until then.

2024-06-28 08:53 UTC, DennRoy commented
Some additional details: I'm actually unable to process embedded samples for 2017. There's an error about the unavailability of DeepTau v2.1 branches in the input (only v2 seems to be available in there). The other eras (2016, 2016_HIMP, 2018) work fine though.

But apparently there's no problem for the KIT people when producing v9 NanoAODs.

2024-07-05 09:47 UTC, kandrosov commented
@DennRoy thanks for the update.
- Since this modification is Run 2 specific, I propose that you change the target branch from `main` to `HTT_skim_v1` so that embedded samples can be produced under the same conditions as the other Run 2 skims.
- You can run missing DeepTau v2p1 on top of miniAOD. It can be done by adding it to [idsToAdd](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py#L250-L259) for embedded samples. Similar to how v2p5 was added to Run 2 skims.

2025-05-22 08:34 UTC, kandrosov commented
Since there are no plans to rerun Run 2 UL skims and go directly to nano v15 for Run 2, I will close this PR.

2025-05-22 08:34 UTC, closed without merging