ZZbbtautau analysis samples
cms-tau-pog/NanoProd pull request #24
Opened 2023-10-31 09:38 UTC by elenavernazza

Samples needed for the ZZbbtautau validation analysis

2023-10-31 15:48 UTC, kandrosov commented
@elenavernazza please resolve conflicts

2023-11-02 08:36 UTC, kandrosov requested changes

2023-11-02 08:36 UTC, kandrosov commented on NanoProd/crab/Run2_2016/TTX.yaml
> +TTZZ: /TTZZ_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM
Please add TTHH samples for completeness (same for other eras)
```
/TTHHTo2B2Tau_HEFT_c2-3_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/TTHHTo2B2Tau_HEFT_c2-6_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/TTHHTo2B2Tau_HEFT_c2-m1_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/TTHHTo2B2Tau_HEFT_kl-0p5_c2-1_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/TTHHTo2B2Tau_HEFT_kl-2_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/TTHHTo2B2Tau_HEFT_kl-3_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/TTHHTo2B2Tau_HEFT_kt-2_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/TTHHTo2B2Tau_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
```

2023-11-02 09:19 UTC, DennRoy commented
Hi, I have a comment and a question:
- Some of the HTauTau samples you're adding in the `Higgs.yaml` files are already present. Can you remove the duplicates?
- You're adding 2016 samples, but don't you need 2016_HIPM samples as well?

2023-11-02 10:08 UTC, elenavernazza commented
Hi, thank you for checking!
The changes should be implemented in the last commits, please let me know if any other correction is needed.
Best,

Elena

2023-11-02 10:12 UTC, DennRoy commented on NanoProd/crab/Run2_2016_HIPM/TTX.yaml
> +    era: Run2_2016
`era: Run2_2016_HIPM`

2023-11-02 10:19 UTC, kandrosov approved these changes
@elenavernazza thank you!

2023-11-02 10:22 UTC, DennRoy commented
Actually I notice the `/ttHToNonbb_M125_TuneCP5_13TeV-powheg-pythia8/...` dataset are still duplicate in the `Higgs.yaml` files. Could you please remove those too?
Secondly, I wonder if for consistency, the Higgs samples you added should have `_M125` in the names, like the other samples, but I'll leave that to you

2023-11-02 14:54 UTC, kandrosov approved these changes

2023-11-02 15:10 UTC, DennRoy approved these changes
Thanks! I have no other comments

2023-11-02 15:27 UTC, merged