New 2022 samples
cms-tau-pog/NanoProd pull request #31
Opened 2023-12-18 14:53 UTC by DennRoy

It took a while, but now most 2022 samples are available in ReReco MiniAODv4 format. Two samples are still stuck in production:
- 2022EE ZZ->2L2Q extension sample
- 2022EE DY->TauTau->MuTau
I can keep an eye on these two samples and uncomment their entries once they're available.

2023-12-18 18:30 UTC, kandrosov commented on NanoProd/crab/Run3_2022EE/dataFG.yaml
>      era: Run3_2022FG
should we change the globaltag?

2023-12-19 10:39 UTC, DennRoy commented on NanoProd/crab/Run3_2022EE/dataFG.yaml
>      era: Run3_2022FG
My understanding is that the GTs we need, the ones listed [here](https://cms-talk.web.cern.ch/t/mc-offline-rereco-gts-for-2022-remini-nano-v12-in-130x/29645), are the ones that are already defined in RunKit

2023-12-19 16:20 UTC, kandrosov commented on NanoProd/crab/Run3_2022EE/dataFG.yaml
>      era: Run3_2022FG
hm.. perhaps I'm looking in the wrong place, but those GTs are for 2022FG PromptReco. Weren't there any changes for Mini v4 ReReco?

2023-12-19 16:59 UTC, DennRoy commented on NanoProd/crab/Run3_2022EE/dataFG.yaml
>      era: Run3_2022FG
I think the previous MiniV3 and NanoV11 GTs were all `124X_...`, while the new ones are `130X_`. And they do call it a "partial ReReco" for data in the link above

2023-12-19 17:10 UTC, kandrosov commented on NanoProd/crab/Run3_2022EE/dataFG.yaml
>      era: Run3_2022FG
ok, I see. thanks for the explanations! it seems that we are all good with the current setup then.

2023-12-19 17:13 UTC, kandrosov requested changes
@DennRoy  could you please also include all the samples requested by Aliaksei in the MM thread? thanks!

2023-12-21 21:06 UTC, kandrosov approved these changes

2023-12-21 22:13 UTC, merged